config/routes.rb
IJURY::Application.routes.draw do

  root to: 'pages#dashboard'


  resources :users
  resources :sessions, only: [:destroy, :create]
  resources :evidences
  get '/test', to: 'pages#test', as: 'test'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  resources :cases do
    resources :ballots
    resources :comments
  end
  resources :votes

  # google omniauth
  get 'google/create'
  get 'google/destroy'
  get 'auth/:provider/callback', to: 'google#create'
  get 'auth/failure', to: redirect('/')
  get 'gsignout', to: 'google#destroy', as: 'gsignout'

  resources :google, only: [:create, :destroy]


end

app/models/evidence.rb
class Evidence < ActiveRecord::Base
  attr_accessible :argument, :video_url, :photo_url, :cases_user_id

  validates :argument, presence: true

end

app/controllers/evidences_controller.rb
class EvidencesController < ApplicationController

  def new
    session[:case_user_plaintiff] = params[:case_user_plaintiff]

    if session[:id]
      @target_user = User.find(session[:id])
      @my_cases = User.find(session[:id]).cases.order('status').order('created_at')

      @my_invites = User.find(session[:id]).cases.where(status: "pending")

    end
      @active_cases = Case.where(status: "active")
      @closed_cases = Case.where(status: "closed")
  end

  def create
    if params[:case_id].blank?
      @evidence = Evidence.create!({
        argument: params["argument"],
        video_url: params["video_url"],
        photo_url: params["photo_url"],
        cases_user_id: params["case_user_plaintiff"]
      })
    end
    if params[:case_id] == "" || params[:case_id] == nil
      @evidence = Evidence.create(argument: params["argument"], video_url: params["video_url"], photo_url: params["photo_url"], cases_user_id: params[:case_user_plaintiff])

      redirect_to dashboard_path
    else
      cases_user = CasesUser.find_by_user_id_and_case_id(session[:id], params[:case_id])

      @evidence = Evidence.create!({
        argument: params["argument"],
        video_url: params["video_url"],
        photo_url: params["photo_url"],
        cases_user_id: cases_user.id
      })

      kase = Case.find(params[:case_id])
      kase.update_attributes!(status: "active", active_start: Time.now, active_end: Time.now + 24.hours)

      redirect_to dashboard_path

    end
  end

end

app/views/evidences/_evidencebody.html.erb
<div id="active_cases_header">
    <span class="cases_ribbon">&nbsp; D a s h b o a r d &nbsp;&nbsp;&nbsp; f o r &nbsp;&nbsp;&nbsp; "<%= User.find(session[:id]).user_name %>"</span>
</div>
  <div id="new_evidence_form">
    <span id="new_evidence_header">Submit your story</span>
    <%= form_tag evidences_path do %>

  <!--  Not using photo URL for MVP
  label_tag "Photo URL" %>
  text_field_tag :photo_url %>
  -->
    <% if current_user %>
    <center>
      <div class="google-auth">
        Signed in to Google as <strong><%= current_user.name %></strong>!<br>
        <%= link_to "Sign out", gsignout_path, id: "sign_out" %><br>
      </div>

      <div id="video-status">No video uploaded yet</p></div>

      <div id="widget"></div>
      <div id="player"></div><br>

      <%= hidden_field_tag :video_url %>

    <% else %>
      <div class="google-auth">
        <%= link_to "Sign in to Google to upload your video", "/auth/google_oauth2", id: "sign_in" %>
      </div>

    <% end %>

    <p>Argument</p>
    <%= text_area_tag :argument %>
    <%= hidden_field_tag :case_id, params[:id] %>
    <%= hidden_field_tag :case_user_plaintiff, params["case_user_plaintiff"] %>
    <br><br>
    <%= submit_tag "Submit Argument" %>
  </end>
  <% end %>
</center>
</div>

app/views/evidences/new.html.erb
<%= render partial: "evidencebody" %>