config/routes.rb
IJURY::Application.routes.draw do

  root to: 'pages#dashboard'


  resources :users
  resources :sessions, only: [:destroy, :create]
  resources :evidences
  get '/test', to: 'pages#test', as: 'test'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  resources :cases do
    resources :ballots
    resources :comments
  end
  resources :votes

  # google omniauth
  get 'google/create'
  get 'google/destroy'
  get 'auth/:provider/callback', to: 'google#create'
  get 'auth/failure', to: redirect('/')
  get 'gsignout', to: 'google#destroy', as: 'gsignout'

  resources :google, only: [:create, :destroy]


end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  layout "special", except: [:new,:create,:create_case_params,:create_plaintiff_params,:create_defendant_params]

  def new
    if session[:id]
      @target_user = User.find(session[:id])
      @my_cases = User.find(session[:id]).cases.order('status').order('created_at')

      @my_invites = User.find(session[:id]).cases.where(status: "pending")

    end
      @active_cases = Case.where(status: "active")
      @closed_cases = Case.where(status: "closed")

  end


  def create
    if User.find_by_user_name(params["defendant_user_name"]) == nil
      redirect_to new_case_path
    else
    create_case_params
    @new_case = Case.create(@case_params)
    create_plaintiff_params
    create_defendant_params
    @case_user_plaintiff = CasesUser.create(@plaintiff_params)
    CasesUser.create(@defendant_params)
    redirect_to new_evidence_path(:case_user_plaintiff => @case_user_plaintiff)
    end
  end


  def create_case_params
    @case_params = {title: params[:title], summary: params[:summary]}
  end

  def create_plaintiff_params
    @plaintiff_params = {case_id: @new_case.id, user_id: session[:id], party: "plaintiff"}
  end

  def create_defendant_params
    @defendant_params = {case_id: @new_case.id, user_id: User.find_by_user_name(params[:defendant_user_name]).id, party: "defendant"}
  end









  def show
    if session[:id]
      @target_user = User.find(session[:id])
      @my_cases = User.find(session[:id]).cases.order('status').order('created_at')

      @my_invites = User.find(session[:id]).cases.where(status: "pending")

    end
      @active_cases = Case.where(status: "active")
      @closed_cases = Case.where(status: "closed")
      @case = Case.find(params[:id])
      session[:case_id] = params[:id]

    @case = Case.find(params[:id])
    session[:case_id] = params[:id]

    # Countdown timer feature
    if @case.active_end == nil
      @starting_seconds = 0
    else
      @starting_seconds = @case.active_end - Time.now
    end

    if @starting_seconds <= 0
      @remaining_days = 0
      @remaining_hours = 0
      @remaining_minutes = 0
      @remaining_seconds = 0
    else
      @remaining_days = @starting_seconds.divmod(84000)[0]
      @remaining_hours = @starting_seconds.divmod(84000)[1].divmod(3600)[0]
      @remaining_minutes = @starting_seconds.divmod(84000)[1].divmod(3600)[1].divmod(60)[0]
      @remaining_seconds = @starting_seconds.divmod(84000)[1].divmod(3600)[1].divmod(60)[1].to_int
    end

  end

end

app/views/cases/_activecase.html.erb
<!-- case heading -->
<div id="case_heading">
  <div class="case_title"> Case: <%= @case.title %></div>

  <p><div class="case_summary"><%= @case.summary %></div></p>

  <div class="countdown-timer">
    <h4>Remaining Time to Vote: <%= @remaining_days %><small>d</small>
      <%= @remaining_hours %><small>h</small>
      <%= @remaining_minutes %><small>m</small>
      <%= @remaining_seconds %><small>s</small>
    </h4>
  </div>
</div>
<!-- end -->
<div id="case_details">C a s e &nbsp; D e t a i l s</div>
<!-- start of both cases -->
<div class="both_people">

	<div class="person1">

		<p>PLAINTIFF: <%= @case.users[0].user_name %></p>

		<div class="argumentText1">
			<h3>PLAINTIFF's ARGUMENT</h3>
      <p><%= @case.cases_users[0].evidence.argument %></p>
		</div>

		<div class="video1">
			<iframe id="ytplayer" type="text/html" width="420" height="237" src="http://www.youtube.com/embed/<%= @case.cases_users[0].evidence.video_url %>" frameborder="0" allowfullscreen>
			</iframe>
		</div>

		<div class="vote-plaintiff">
  		<div class="vote-plaintiff-button">Vote for the plaintiff!<%= button_to "Vote", case_ballots_path(role: "plaintiff", case_id: @case.id), :remote => true %></div>

      TOTAL BALLOTS: <span id = 'plaintiff_vote_count'><%= Ballot.where(:role => "plaintiff", :case_id => @case.id).count %></span>
		</div>

	</div>

	<div class="person2">

		<p>DEFENDANT:<%= @case.users[1].user_name %></p>

		<div class="argumentText2">
      <h3> Defendant's Argument </h3>
      <p><%= @case.cases_users[1].evidence.argument %></p>
    </div>

		<div class="video2">
			<iframe id="ytplayer" type="text/html" width="420" height="237" src="http://www.youtube.com/embed/<%= @case.cases_users[1].evidence.video_url %>" frameborder="0" allowfullscreen>
			</iframe>
		</div>


    <div class="vote-defendant">
      <div class="vote-defendant-button">Vote for the defendant!<%= button_to "Vote", case_ballots_path(case_id: @case.id, role: "defendant"), :remote => true %></div>

      TOTAL BALLOTS: <span id = 'defendant_vote_count'><%= Ballot.where(:role => "defendant", :case_id => @case.id).count %></span>
    </div>
    <br/>
<!-- for person 2 -->
  </div>
<!-- for both people -->
</div>






<div id="case_details">C o m m e n t s</div>

<div id="comment_section">
  <center>
<div class="commentsBox">
  <h3>Comment</h3>
  <% @comment = Comment.new %>
  <%= form_for [@case, @comment], :url => case_comments_path(@case, @comment), remote: true do |f| %>
    <%= f.text_area :body, cols: 40, rows: 7 %>
    <%= f.submit "Submit"%>
  <% end %>
  <!-- closes box -->
</div>
</center>

	<div id ="commentslist">
	<br>
  <% @case.comments.each do |comment| %>
      <div class="comments_bundle">
	    <p><b><%= User.find(comment.user_id).user_name %></b>: <%= comment.body %></p>
	    <%= button_to "Like", votes_path(direction: "up", comment_id: comment.id, user_id: session[:id]), remote: true, :form => { :id => "like", "data-type" => "json" } %>
	    <%= button_to "Dislike", votes_path(direction: "down", comment_id: comment.id, user_id: session[:id]), remote: true, :form => { :id => "dislike", "data-type" => "json" } %>
	    <p>Likes: <span class="<%= comment.id %>up"><%= comment.votes.where(:direction => "up").count %></span>
	    Dislikes: <span class="<%= comment.id %>down"><%= comment.votes.where(:direction => "down").count %></span>
	  </p>
    </div>
    <% end %>
  </div>
</div>

app/views/cases/_casebody.html.erb
<% if @case.status == "pending" && session[:id] == @case.cases_users[0].user_id %>
	<%= render partial: "previewcase" %>

<% elsif @case.status == "pending" && session[:id] == @case.cases_users[1].user_id %>
	<%= render partial: "/evidences/evidencebody" %>

<% elsif @case.status == "pending" %>
	<p> Case is not available yet.  Come back soon! </p>

<% elsif @case.status == "active" %>

  <%= render partial: "activecase" %>

<% elsif @case.status == "closed"  %>

  <%= render partial: "closedcase" %>

<% else %>

  <p> Hmm... didn't plan this scenario.</p>

<% end %>

app/views/cases/_closedcase.html.erb
<div class="cases_show_main_body">
	<!-- start of heading -->
	<div id="case_heading">
		<h2>CASE DISMISSED!</h2>

		PLAINTIFF: <%= @case.users[0].user_name %> had <%= Ballot.where(:role => "plaintiff", :case_id => @case.id).count %> votes
		<br>
   	DEFENDANT:<%= @case.users[1].user_name %> had <%= Ballot.where(:role => "defendant", :case_id => @case.id).count %> votes

   	<% if ((Ballot.where(:role => "plaintiff", :case_id => @case.id).count) > (Ballot.where(:role => "defendant", :case_id => @case.id).count))%>
   		<p>PLAINTIFF WINS!</p>
 		<% elsif((Ballot.where(:role => "plaintiff", :case_id => @case.id).count) < (Ballot.where(:role => "defendant", :case_id => @case.id).count))%>
 			<p>DEFENDANT WINS!</p>
 		<% else %>
   		<p>IT'S A TIE!</p>
   	<% end %>
	</div>
<!-- end -->



	<div id="case_details">C a s e &nbsp; D e t a i l s</div>
	<center>
			<h3><%= @case.title %></h3>
	</center>


<div class="both_people">

	<div class="person1">

		PLAINTIFF: <%= @case.users[0].user_name %>

		<div class="argumentText1">
			PLAINTIFF's ARGUMENT: <%= @case.cases_users[0].evidence.argument %>
		</div>

		<div class="video1">
			<iframe id="ytplayer" type="text/html" width="420" height="237" src="http://www.youtube.com/embed/<%= @case.cases_users[0].evidence.video_url %>" frameborder="0" allowfullscreen>
			</iframe>
		</div>


	</div>
<!-- end of person 1 -->
	<div class="person2">

		DEFENDANT:<%= @case.users[1].user_name %>

		<div class="argumentText2">
			Defendant's ARGUMENT: <%= @case.cases_users[1].evidence.argument %>
		</div>

		<div class="video2">
			<iframe id="ytplayer" type="text/html" width="420" height="237" src="http://www.youtube.com/embed/<%= @case.cases_users[1].evidence.video_url %>" frameborder="0" allowfullscreen>
			</iframe>
		</div>
	</div>
</div>


<div id="comment_section">
<div class="commentsBox">

	<div id = "commentslist">
		<br>
		<% @case.comments.each do |comment| %>
		    <p><b><%= User.find(comment.user_id).user_name %></b>: <%= comment.body %></p>
		    <p>
		    Up-Votes: <%= comment.votes.where(:direction => "up").count %> -
		    Down-Votes: <%= comment.votes.where(:direction => "down").count %>
		  </p>
		  <% end %>
	</div>
</div>
</div>


<!-- cases show main body -->
</div>

app/views/cases/_previewcase.html.erb
	<h3>Case Preview</h3>

	<div><%= @case.title %></div>

	<div class="person1">

		PLAINTIFF: <%= @case.users[0].user_name %>

		<div class="argumentText1">
		</div>

		<div class="video1">
			<iframe id="ytplayer" type="text/html" width="420" height="237" src="http://www.youtube.com/embed/<%= @case.cases_users[0].evidence.video_url %>" frameborder="0" allowfullscreen>
			</iframe>
		</div>

	</div>

	<div class="person2">

		DEFENDANT:<%= @case.users[1].user_name %>

		<div class="case-message">
			Awaiting argument from your opponent...
		</div>

	</div>
	

app/views/cases/new.html.erb
<div id="active_cases_header">
    <span class="cases_ribbon">&nbsp; D a s h b o a r d &nbsp;&nbsp;&nbsp; f o r &nbsp;&nbsp;&nbsp; "<%= User.find(session[:id]).user_name %>"</span>
</div>
<div id="crazy">
<div id="create_case_box">
  <span id="new_case_title">Create a New Case</span>
  <div id="case_form_div">
  <%= form_tag cases_path,:id => 'create_case_form' do %>
    <p>Title</p>
    <%= text_field_tag :title , nil, :class => 'input_box'%>
    <p>Summary</p>
    <%= text_area_tag :summary %>
    <p>Defendant</p>
    <%= text_field_tag :defendant_user_name %>

    <%= submit_tag "Create Case"%>
  <% end %>
  <div>
</div>
</div>

app/views/cases/show.html.erb
<%= render 'casebody' %>